# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'smack' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for smack
  
  pod 'Alamofire'
  pod 'SwiftyJSON'
  pod 'Socket.IO-Client-Swift'

end
